name = "Pingouin"
uuid = "61ac1d4c-5a1f-4019-949c-7919748f8c44"
authors = ["Cl√©ment POIRET <poiret.clement@outlook.fr>"]
version = "0.2.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
CSV = ">= 0.8"
DataFrames = ">= 0.22"
Distributions = ">= 0.23"
HypergeometricFunctions = ">= 0.3"
HypothesisTests = ">= 0.10"
QuadGK = "^2.4"
SpecialFunctions = ">= 0.10"
StatsBase = ">= 0.33"
StatsFuns = ">= 0.9"
julia = ">= 1.0"
